export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_CHECK_LOCAL_STORE_START = 'AUTH_CHECK_LOCAL_STORE_START';
export const AUTH_CHECK_LOCAL_STORE_SUCCESS = 'AUTH_CHECK_LOCAL_STORE_SUCCESS';
export const AUTH_CHECK_LOCAL_STORE_FAIL = 'AUTH_CHECK_LOCAL_STORE_FAIL';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

// Contexts Actions
export const GET_CONTEXTS_START = 'GET_CONTEXTS_START';
export const GET_CONTEXTS_SUCCESS = 'GET_CONTEXTS_SUCCESS';
export const GET_CONTEXTS_FAIL = 'GET_CONTEXTS_FAIL';

export const GET_CONTEXT_START = 'GET_CONTEXT_START';
export const GET_CONTEXT_SUCCESS = 'GET_CONTEXT_SUCCESS';
export const GET_CONTEXT_FAIL = 'GET_CONTEXT_FAIL';

export const SAVE_CONTEXT_START = 'SAVE_CONTEXT_START';
export const SAVE_CONTEXT_SUCCESS = 'SAVE_CONTEXT_SUCCESS';
export const SAVE_CONTEXT_FAIL = 'SAVE_CONTEXT_FAIL';

export const UPDATE_CONTEXT_START = 'UPDATE_CONTEXT_START';
export const UPDATE_CONTEXT_SUCCESS = 'UPDATE_CONTEXT_SUCCESS';
export const UPDATE_CONTEXT_FAIL = 'UPDATE_CONTEXT_FAIL';

export const DELETE_CONTEXT_START = 'DELETE_CONTEXT_START';
export const DELETE_CONTEXT_SUCCESS = 'DELETE_CONTEXT_SUCCESS';
export const DELETE_CONTEXT_FAIL = 'DELETE_CONTEXT_FAIL';

// Endpoints Actions
export const GET_ENDPOINTS_START = 'GET_ENDPOINTS_START';
export const GET_ENDPOINTS_SUCCESS = 'GET_ENDPOINTS_SUCCESS';
export const GET_ENDPOINTS_FAIL = 'GET_ENDPOINTS_FAIL';

export const GET_ENDPOINT_EDIT_START = 'GET_ENDPOINT_EDIT_START';
export const GET_ENDPOINT_EDIT_END = 'GET_ENDPOINT_EDIT_END';

export const SAVE_ENDPOINT_START = 'SAVE_ENDPOINT_START';
export const SAVE_ENDPOINT_SUCCESS = 'SAVE_ENDPOINT_SUCCESS';
export const SAVE_ENDPOINT_FAIL = 'SAVE_ENDPOINT_FAIL';

export const DELETE_ENDPOINT_START = 'DELETE_ENDPOINT_START';
export const DELETE_ENDPOINT_SUCCESS = 'DELETE_ENDPOINT_SUCCESS';
export const DELETE_ENDPOINT_FAIL = 'DELETE_ENDPOINT_FAIL';

export const SAVE_SEARCH_KEY = 'SAVE_SEARCH_KEY';